[project]
name = "PerMeA"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "environs",
    "loguru",
    "tqdm",
    "typer",

    "pydantic",

    "jinja2",
    "python-multipart",
    "starlette",
    "uvicorn[standard]",

    # "sparqlwrapper",
    # "rdflib",
]

[project.optional-dependencies]
dev = ["black", "isort", "ipython", "pytest"]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["app"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
