services:
  oxigraph:
    container_name: permea-oxigraph
    image: oxigraph/oxigraph
    ports:
      - "7878:7878"
    volumes:
      - ".data/docker/oxigraph:/data"
  
  jena-fuseki:
    container_name: jena-fuseki
    image: stain/jena-fuseki
    ports:
      - "${DOCKER_JENA_FUSEKI_PORT:-3030}:3030"
    environment:
      - JVM_ARGS=-Xmx2g
      - ADMIN_PASSWORD=${DOCKER_JENA_FUSEKI_ADMIN_PASSWORD}
    volumes:
      - ".data/docker/fuseki-data:/fuseki"